apiVersion: v1
kind: Service
metadata:
  name: measurement-api
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    pod: measurement-api
spec:
  type: {{ .Values.service.type }}
  {{ if eq .Values.service.type  "LoadBalancer" }}
  loadBalancerIP: {{ .Values.service.ip }}
  {{- end }}
  selector:
    pod: measurement-api
  ports:
  - name: measurement-api
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
